# Generated by Django 4.1.4 on 2023-06-06 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Accessory name')),
                ('color', models.CharField(max_length=50, verbose_name='Accessory color')),
                ('description', models.CharField(max_length=100, verbose_name='Accessory description')),
                ('price', models.FloatField(verbose_name='Accessory price')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Accessory brand')),
                ('accessories', models.ManyToManyField(related_name='brand_set', to='tasks.accessory', verbose_name='Accessories')),
            ],
        ),
        migrations.AddField(
            model_name='accessory',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_set', to='tasks.brand', verbose_name='Brand'),
        ),
    ]
