# Generated by Django 4.2 on 2023-06-17 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Accessory name')),
                ('color', models.CharField(max_length=50, verbose_name='Accessory color')),
                ('description', models.CharField(max_length=100, verbose_name='Accessory description')),
                ('image', models.FileField(null=True, upload_to='', verbose_name='Accessory image')),
                ('price', models.FloatField(verbose_name='Accessory price')),
                ('brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.brand', verbose_name='Brand')),
                ('categories', models.ManyToManyField(to='tasks.category', verbose_name='Categories')),
            ],
        ),
    ]
