# Generated by Django 4.1.4 on 2023-06-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='image',
            field=models.FileField(null=True, upload_to='', verbose_name='Accessory image'),
        ),
    ]
