# Generated by Django 4.2 on 2023-06-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Accessory image'),
        ),
    ]
