# Generated by Django 4.2 on 2023-05-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Accesory name')),
                ('brand', models.CharField(max_length=20, verbose_name='Accesory name')),
                ('color', models.CharField(max_length=20, verbose_name='Accesory name')),
                ('description', models.CharField(max_length=20, verbose_name='Accesory name')),
                ('image', models.FileField(upload_to='')),
                ('price', models.FloatField()),
            ],
        ),
    ]
