# Generated by Django 4.2 on 2023-05-22 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_accesory_brand_alter_accesory_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesory',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tasks.user', verbose_name='Usuario'),
        ),
    ]
