# Generated by Django 4.2 on 2023-05-22 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_accesory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesory',
            name='user',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='tasks.user', verbose_name='Usuario'),
        ),
    ]
