# Generated by Django 4.2 on 2023-05-25 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_accesory_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Accesory name')),
                ('color', models.CharField(max_length=50, verbose_name='Accesory color')),
                ('brand', models.CharField(max_length=50, verbose_name='Accesory brand')),
                ('description', models.CharField(max_length=100, verbose_name='Accesory description')),
                ('image', models.FileField(upload_to='', verbose_name='Accesory image')),
                ('price', models.FloatField(verbose_name='Accesory price')),
            ],
        ),
        migrations.DeleteModel(
            name='Accesory',
        ),
        migrations.AddField(
            model_name='user',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='tasks.accessory'),
        ),
    ]
