# Generated by Django 4.2 on 2023-05-25 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_accessory_delete_accesory_user_accessory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accessory',
        ),
        migrations.AddField(
            model_name='accessory',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='tasks.user'),
        ),
    ]
